apiVersion: v1
kind: ConfigMap
metadata:
  namespace: cloudstate-system
  name: cloudstate-config
data:
  config.yaml: |
    noStore:
      image: akkaserverless/akkaserverless-proxy-native-core:latest
      # args:
      # - "-Dconfig.resource=no-store.conf"
    inMemory:
      image: akkaserverless/akkaserverless-proxy-native-core:latest
      # args:
      # - "-Dconfig.resource=in-memory.conf"
    postgres:
      image: akkaserverless/akkaserverless-proxy-native-postgres:latest
    cassandra:
      image: akkaserverless/akkaserverless-proxy-native-cassandra:latest
