apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: statefulstores.cloudstate.io
spec:
  group: cloudstate.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: statefulstores
    singular: statefulstore
    kind: StatefulStore
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: Type
    type: string
    description: The type of stateful store
    JSONPath: .spec.type
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp

